git:
    submodules: false
sudo: required
language: go
go:
  - 1.9
services:
  - docker
before_install:
  - docker pull alpine
  - export GOPATH="${TRAVIS_BUILD_DIR}"
  - go get github.com/mattn/goveralls
  - go build github.com/mattn/goveralls
  - cd src
install:
  - go get -t ./...
before_script:
  - cd ${TRAVIS_BUILD_DIR}
script:
  - ./full_build_and_test.sh
after_script:
  - ./goveralls -coverprofile=units.cov -service=travis-ci -repotoken=$COVERALLS_TOKEN
